#ServerProperties
server:
  port: 8081
  servlet:
    context-path: /community



spring:
  thymeleaf:
    cache: false
  application:
    name: community
  #datasource
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/community
      username: root
      password: 123456
  # mail
  mail:
    host: smtp.sina.com
    port: 465
    username: ls18995420961@sina.com
    password: 522c0f89f61e4820
    protocol: smtps
    properties.mail.stmp.ssl.enable: true
    # redisProperties
  redis:
    database: 1
    host: 192.168.88.130
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  # kafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  data:
    elasticsearch:
      repositories:
        enabled: true
      uris: 127.0.0.1:9300
  #ElasticsearchProperties
# ElasticsearchProperties
#spring.data.elasticsearch.cluster-name=my-cluster
#spring.data.elasticsearch.cluster-nodes=centos:9300











# mybatis
mybatis:
  type-aliases-package: com.example.community
  mapper-locations: classpath:com/example/community/mapper/*.xml

#logger
#logging:
#  level:
#    com.example.community: debug
#  file:
#    name: d:/springboot/community/community.log

#community
community:
  path:
    domain: http://localhost:8081
    fileNamePath: d:/work/data/upload

